### ISSUE TITLE
腾讯云问题：云函数创建失败，有人遇到同样的情况吗？

### ISSUE THREAD

**Issue by Kenny-Ch** [y1ndan/genshinhelper#11]
使用的是serverless的包，但是在创建就失败了，而且也没有报错失败原因。
![image](https://user-images.githubusercontent.com/54130213/119432941-cf1c5400-bd47-11eb-8ed4-86d95f6f9d52.png)

**Comment by Kenny-Ch** [comment]
这种情况要交工单啥的嘛？

**Comment by y1ndan** [comment]
问下客服看看
