### ISSUE TITLE
能否忽略配置文件中不存在的字段啊

### ISSUE THREAD

**Issue by onlymash** [y1ndan/genshinhelper#15]
无意中更新了版本，但是json配置文件并没有更新，少了"cookie_miyoubi"字段，运行时报错，几天后才发现，这时候已经漏签了几天了

**Comment by y1ndan** [comment]
这个确实是疏忽了，忘记提醒更新配置文件。

根据你的情况，参照模板自行添加这个字段到现有配置文件就行了。

**Comment by onlymash** [comment]
可以简化一下，不想配置的选项可以不写进配置文件里，读取时没有配置的选项默认为空值就好，运行时不应该报错。

**Comment by onlymash** [comment]
更新到了1.2.0，我把多余的配置删除了，只保留这三项
```
{
        "LANGUAGE": "en-us",
        "COOKIE_MIHOYOBBS": "cookie",
        "COOKIE_HOYOLAB": "cookie"
}

```
能签到成功，但最后会报一个错误，说明json解析还存在一点小问题
```
2021-06-03 01:19:59 ERROR Expecting value: line 1 column 1 (char 0)
2021-06-03 01:19:59 INFO End of process run
```

**Comment by y1ndan** [comment]
更新1.2.1看看还有没有这个问题

**Comment by onlymash** [comment]
刚更新1.2.1 已经没有这条错误提示了
