### ISSUE TITLE
【小小建议】关于mybcookie

### ISSUE THREAD

**Issue by lmj731** [y1ndan/genshinhelper#18]
可以将程序请求得到的mybcookie展示出来，提醒用户写入配置中，然后这里直接替换，避免程序中断的不友好体验：
![image](https://user-images.githubusercontent.com/39516838/120417832-15019980-c392-11eb-95b0-4414089d1844.png)

**Comment by y1ndan** [comment]
这个问题可以看下 #14 的回复。
