### ISSUE TITLE
腾讯云问题

### ISSUE THREAD

**Issue by ZiXia1** [y1ndan/genshinhelper#2]
函数创建中...
函数创建失败, 失败原因：
未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by y1ndan** [comment]
不知道你如何操作？是否下载了云函数包？
下载：https://wwa.lanzoux.com/b07mk6dla
密码：ed03

**Comment by ZiXia1** [comment]
> 不知道你如何操作？是否下载了云函数包？
> 下载：https://wwa.lanzoux.com/b07mk6dla
> 密码：ed03

好的，谢谢。为什么链接不放在GitHub上

**Comment by YuukyuuKikan** [comment]
阿里云同样的问题，不使用serverless版本就会报错
这个版本藏的真深。github没有，中文教程链接过去404

**Comment by y1ndan** [comment]
> 阿里云同样的问题，不使用serverless版本就会报错
> 
> 这个版本藏的真深。github没有，中文教程链接过去404

嘛 历史遗留问题hhh
