### ISSUE TITLE
米游币获取执行方面的小建议

### ISSUE THREAD

**Issue by Womsxd** [y1ndan/genshinhelper#20]
https://bbs-api.mihoyo.com/apihub/sapi/getUserMissionsState
使用这个api(get方法)来获取已经完成了的任务，防止每日重复运行后重复执行，同时也可以靠这个api获取每日可以获得多少米游币(data.can_get_points)和账号里面有多少米游币(data.total_points)
返回的json里面data.states里面的mission_id 58,59,60,61分别对应讨论区签到,看3个帖子,点赞5次,分享一次
~~(以及有考虑整隔壁崩坏3社区的每日签到吗？((((~~

**Comment by y1ndan** [comment]
感谢建议，已增加检测。

崩三目前没有计划

**Comment by Womsxd** [comment]
不知道有没有做好空文本的检测，因为没执行过的话那4个id是不会出现的(
~~以及崩3的社区我已经抓包完事了~~

**Comment by y1ndan** [comment]
什么空文本检测

**Comment by Womsxd** [comment]
> 什么空文本检测

可能是我表述有问题，反正就是这个api获取到内容后比如你没做讨论区签到(58)，那么返回的json里面mission_id就没有58

> ```json
>{
	"retcode":0,
	"message":"OK",
	"data":{
		"states":[
			{
				"mission_id":62,
				"process":1,
				"happened_times":1,
				"is_get_award":true,
				"mission_key":"bind_game_role_0"
			},
			{
				"mission_id":63,
				"process":1,
				"happened_times":1,
				"is_get_award":true,
				"mission_key":"verified_0"
			},
			{
				"mission_id":64,
				"process":1,
				"happened_times":1,
				"is_get_award":true,
				"mission_key":"modify_signature_0"
			}
		],
		"already_received_points":0,
		"total_points":已经获得的米游币的数量,
		"today_total_points":110,
		"is_unclaimed":false,
		"can_get_points":110
	}
}
>```

**Comment by y1ndan** [comment]
不影响，不然今天签到也不会成功。
