### ISSUE TITLE
Error when using this only for HoyoLab.

### ISSUE THREAD

**Issue by TheraNinjaCat** [y1ndan/genshinhelper#21]
Commit 21bbc314adb5b52b929b8070564d6b8f759b7b39 added travel notes to the output. This requires the variable `travel_notes` be set on line 130 of `genshin.py`, however if `region` is not either `'cn_gf01'`, or `'cn_qd01'` this is never set, leading to the following error:

```
2021-06-08 14:31:34 ERROR TRACEBACK
Traceback (most recent call last):
  File "/app/genshinhelper/__init__.py", line 58, in __run_sign
    result = func(cookie).run()
  File "/app/genshinhelper/genshin.py", line 59, in wrapper
    return func(self, *args, **kwargs)
  File "/app/genshinhelper/genshin.py", line 130, in run
    'travel_notes': travel_notes,
UnboundLocalError: local variable 'travel_notes' referenced before assignment
```

This region field seems to only ever be set if the class name includes `Yuanshen`, hence if the GenshinCheckin class is being used this will always error.

One potential fix could be to assign `travel_notes = None` above line 119, or `travel_notes` could be set to something generic in an `else` block after the `if` block on line 119, or the `message` object assignment on line 125 could be surrounded in a `try except` block where `message` is set without `travel_notes` if it encounters a `NameError`. These are just ideas, I'll leave it up to whoever actually writes the fix to decide what's best.

**Comment by y1ndan** [comment]
Hi TheraNinjaCat, thanks for your feedback. Presetting a value for travel_notes is an easy and effective way, I will fix it later.

**Comment by TheraNinjaCat** [comment]
That seems to have done the trick, this can probably be closed now.
