### ISSUE TITLE
"TZ=Asia/Shanghai" in dockerfile is no use for alpine

### ISSUE THREAD

**Issue by cokebar** [y1ndan/genshinhelper#23]
alpine image doesn't support this method.
you should manually copy tzdata file instead 
```
apk update && apk add tzdata
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
echo "Asia/Shanghai" > /etc/timezone
apk del tzdata
```

**Comment by y1ndan** [comment]
The current Dockerfile is OK.

My test result is that if you don't remove the `tzdata`, just set the `TZ` environment variable to the time zone you want and it will work well.

```
/app $ date -R
Thu, 10 Jun 2021 00:11:52 +0800
/app $ export TZ="America/Los_Angeles"
/app $ date -R
Wed, 09 Jun 2021 09:30:22 -0700
```

**Comment by TheraNinjaCat** [comment]
The package `tzdata` is installed by the `python:3-alpine` [image](https://hub.docker.com/layers/python/library/python/alpine/images/sha256-2dd55073bf996f367008a7fad490add0343b5c151b708dcf52c133f70ab171a9?context=explore) (line 5) used in the current Dockerfile. This is also true of the arm Dockerfiles.
`tzdata` includes timezone data for all timezones, and as such is relatively large in size. As such, the recommended way of using this in an alpine linux container is to install `tzdata`, copy the required data to `/etc/localtime`, write the name of it to `/etc/timezone`, then uninstall `tzdata`, as demonstrated by the original issue. It is incorrect however to suggest that the `TZ=Asia/Shanghai` method isn't supported, it's simply not recommended as the point of alpine linux is to be small, and including a lot of unused `tzdata` is wasteful. With `tzdata` installed, and `TZ=Asia/Shanghai` set, the system will correctly access the timezone data from within `/usr/share/zoneinfo` directly.
`tzdata` is a soft requirement for Python, however if it is missing Python will attempt to use an equivalent package stored in `pypi` so there's not much point in uninstalling it as Python itself is relatively large, and needs it anyway.

**Comment by cokebar** [comment]
Sorry, my mistake. It works well.
I use Synology NAS, and it seems to be a bug for DSM's log system. The time inside the docker container is right, but the time displayed by the DSM log system is not correct.
![Screenshot_20210610-075708__01](https://user-images.githubusercontent.com/9136591/121444463-282fed00-c9c2-11eb-89d2-58638b9b408b.jpg)
