### ISSUE TITLE
Risk of violating github TOS

### ISSUE THREAD

**Issue by Prurite** [y1ndan/genshinhelper#3]
My access of my fork of this repo recently get disabled 'due to a violation of github ToS'.
![图片](https://user-images.githubusercontent.com/44775584/119059746-82f9a880-ba03-11eb-9a63-cf25949a5de7.png)

**Comment by y1ndan** [comment]
**Do not use GitHub Action to run this or my old project**, it is recommended to use docker, if you do not have a host, you can try serverless such as Tencent Cloud or other methods.

**Comment by jgyy** [comment]
do you have guide for AWS, GCP, Azure serverless?

**Comment by y1ndan** [comment]
> do you have guide for AWS, GCP, Azure serverless?

Updated aws guide
