### ISSUE TITLE
签到信息返回'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by SEAFHMC** [y1ndan/genshinhelper#30]
系统：CentOS  8.3 64位
使用poetry创建虚拟环境为：
- python = "^3.9"
- genshinhelper = "^1.4"
- requests ="^2.20.0"
- beautifulsoup4 = "^4.9.3"
- discord-webhook = "^0.12.0"
运行后日志显示：
![image](https://user-images.githubusercontent.com/9484642/125759904-62846285-d5cc-4161-aff2-31a83008d56b.png)

**Comment by y1ndan** [comment]
一般是cookie格式不正确

**Comment by SEAFHMC** [comment]
> 一般是cookie格式不正确

啊，好像是说我缺少login_ticket。但是我复制出来确实没有呀

**Comment by y1ndan** [comment]
> 缺少login_ticket。但是我复制出来确实没有呀
那就只能自行米游社App抓包，或者不配置社区签到。原神签到不需要login_ticket。

**Comment by SEAFHMC** [comment]
谢啦，重新登陆获取Cookie之后成功了
