### ISSUE TITLE
Connect Timeout 錯誤

### ISSUE THREAD

**Issue by WindyHook** [y1ndan/genshinhelper#32]
從昨天開始就不能正常簽到了，今天查 log 發現是由於 timeout 無法建立連接，包括手動 restart container 也無法成功簽到。但是手動嘗試 ping 和 curl 目標 url "api-takumi.mihoyo.com" 是沒問題的。

![image](https://user-images.githubusercontent.com/30546031/126278482-633fd8bc-6133-4b7d-8e5e-238325e58d9c.png)

**Comment by y1ndan** [comment]
是云函数吗？云函数有个持续运行时间的限制，在`v1.5.0`中加入了随机延迟10-300s，执行又要一点时间。
需要把持续运行时间调高一点；或者修改MAX_SLEEP_SECS为适当的值。

**Comment by WindyHook** [comment]
是群暉的 docker，我之前用的是 v1.1.1，是今天發現昨天簽到失敗了才升級的 v1.5.1，但是還是同樣的錯誤情況

**Comment by WindyHook** [comment]
嘗試將 Network 從 bridge 改為 host 後可正常運行。
