### ISSUE TITLE
只配置BH3的Cookie会有问题

### ISSUE THREAD

**Issue by NepPure** [y1ndan/genshinhelper#37]
![~UB@2E`PCF6L5LJBR)(F_ U](https://user-images.githubusercontent.com/12379907/127729665-8e266eba-acaa-45c5-ae4f-7f2de7bd30cd.png)

会提示这个，然后如果米友社账号只有崩3没有原神，原神签到执行出错，也不会继续签到崩3

**Comment by y1ndan** [comment]
看下是不是配置了`COOKIE_BH3`，环境变量或者配置文件都试下。

没有原神账号只能先不配置原神cookie了

**Comment by NepPure** [comment]
这个就是只配置了
`COOKIE_BH3`的提示

不配置原神账号就会提示这个，如果原神的COOKIE也配置了，原神签到会抛出异常，也不会继续进行崩3签到

**Comment by y1ndan** [comment]
测试只配置`COOKIE_BH3 `能签，没成功复现上述问题。

**Comment by NepPure** [comment]
破案了

![image](https://user-images.githubusercontent.com/12379907/127731287-2977f920-5307-410b-a9f4-84871e9be676.png)

是群友蠢了

**Comment by y1ndan** [comment]
有一说一，`zh-cn`改成`zh`才对，不过现在应该不影响。
