### ISSUE TITLE
HoYoLab Community Shows list index out of range

### ISSUE THREAD

**Issue by Evilcat325** [y1ndan/genshinhelper#4]
It seems the hoyolab cookies wasn't parsed correctly?
```
2021-05-21 10:10:02 INFO Starting signing
2021-05-21 10:10:02 INFO 🌀 genshinhelper v1.1.1
2021-05-21 10:10:02 INFO Running process...
2021-05-21 10:10:02 INFO You have 1 「HoYoLAB Community」 account configured.
2021-05-21 10:10:02 INFO Preparing to perform tasks for account 1...
2021-05-21 10:10:02 ERROR 👻 No.1:
    list index out of range
Traceback (most recent call last):
  File "/app/genshinhelper/genshin.py", line 52, in wrapper
    self._sign_data['uid'] = self._cookie.split('account_id=')[
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/genshinhelper/__init__.py", line 34, in __run_sign
    result = func(cookie).run()
  File "/app/genshinhelper/genshin.py", line 55, in wrapper
    raise Exception(e)
Exception: list index out of range
2021-05-21 10:10:02 INFO RESULT:
〓HoYoLAB Community〓
🔰 ✔ 0 · ✖ 1
👻 No.1:
    list index out of range
2021-05-21 10:10:02 INFO Discord 🥳
```

my docker compose yml
```
version: "3"
services:
  genshin:
    image: "yindan/genshinhelper:latest"
    restart: always
    network_mode: host
    environment:
      - CRON_SIGNIN=*/5 * * * *
      - LANGUAGE=zh-cn
      - COOKIE_HOYOLAB=xxxxxxxxxxxxxxxx
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/xxxxxxx
```

**Comment by y1ndan** [comment]
Please check the `COOKIE_HOYOLAB` parameter, it must contain `account_id=xxx` and `cookie_token=xxx`.

**Comment by zzhongzz** [comment]
Same problem here. I think it's because hoyolab uses a different cookie format which does not contain account_id=xxx and cookie_token=xxx. 
My cookie is something like this: "mi18nLang=en-us; _ga=xxxx; _gid=xxxx; _MHYUUID=xxxx; ltoken=xxxx; ltuid=xxxx"

**Comment by y1ndan** [comment]
Go to the following URL to get your cookie:
https://webstatic-sea.mihoyo.com/ys/event/signin-sea/index.html?act_id=e202102251931481&lang=en-us

**Comment by zzhongzz** [comment]
> Go to the following URL to get your cookie:
> https://webstatic-sea.mihoyo.com/ys/event/signin-sea/index.html?act_id=e202102251931481&lang=en-us

Works now, thank you!

**Comment by Evilcat325** [comment]
Oh okay, from the doc, I thought it was to use the cookie login to gain the UID and account info.
Maybe a simple Readme update could include the instruction for the hoyolab configuration that not only the cookie_token but also the account_uid part.

Btw, it seems if you log in first on `hoyolab.com`, you will only getting a `ltoken=xxx; ltuid=1234567` in the cookies, and website use `https://api-os-takumi.mihoyo.com/community/user/wapi/getUserFullInfo` API to get the account uid and other info. 
For cookies to have the account uid and cookie_token. you have to clear the cookie from `hoyolab.com` and log in directly at the mihoyo.com  page.

**Comment by y1ndan** [comment]
> Btw, it seems if you log in first on `hoyolab.com`, you will only getting a `ltoken=xxx; ltuid=1234567` in the cookies, and website use `https://api-os-takumi.mihoyo.com/community/user/wapi/getUserFullInfo` API to get the account uid and other info. 
> 
> For cookies to have the account uid and cookie_token. you have to clear the cookie from `hoyolab.com` and log in directly at the mihoyo.com  page.

A few months ago it was possible to get the `account_id` and `cookie_token` by log in directly on hoyolab.com. Maybe the site has been upgraded now.

**Comment by fluteds** [comment]
> Btw, it seems if you log in first on `hoyolab.com`, you will only getting a `ltoken=xxx; ltuid=1234567` in the cookies, and website use `https://api-os-takumi.mihoyo.com/community/user/wapi/getUserFullInfo` API to get the account uid and other info.
> For cookies to have the account uid and cookie_token. you have to clear the cookie from `hoyolab.com` and log in directly at the mihoyo.com page.

What cookie values did you end up putting in your docker-compose.yml?
