### ISSUE TITLE
pushplus更换推送URL+推送不支持markdown语法

### ISSUE THREAD

**Issue by Yaklo** [y1ndan/genshinhelper#43]
新域名
http://pushplus.hxtrip.com/send

**Comment by Yaklo** [comment]
现在不支持markdown语法 信息都是挤在一起的，目前支持html json两种消息模板

**Comment by AXdouB** [comment]
我临时改了一下 已经开PR了 不妨先试着按照这个修改
我测试过已经可以使用了 格式做到换行正常
https://github.com/y1ndan/genshinhelper/pull/44/files

**Comment by qianxu2001** [comment]
你确定是新域名？明明是老域名啊，之前就是从这个改到 www.pushplus.plus 的，另外没有出现消息异常
![Screenshot_2021-08-23-20-56-25-240_com tencent mm](https://user-images.githubusercontent.com/62287903/130451015-b78abbac-8cf9-4f4f-831e-c9ed7d23a850.jpg)

**Comment by AXdouB** [comment]
> 你确定是新域名？明明是老域名啊，之前就是从这个改到 [www.pushplus.plus](http://www.pushplus.plus) 的，另外没有出现消息异常
> ![Screenshot_2021-08-23-20-56-25-240_com tencent mm](https://user-images.githubusercontent.com/62287903/130451015-b78abbac-8cf9-4f4f-831e-c9ed7d23a850.jpg)

不太清楚 我昨天才开始用的pushplus
用 www.pushplus.plus 就会提示无效的用户 token
用这个 pushplus.hxtrip.com 就是 200，而且只有 html 和 json
难道说 pushplus 有两套用户系统对应两个域名？那是否得考虑新增一个变量了

**Comment by qianxu2001** [comment]
> > 你确定是新域名？明明是老域名啊，之前就是从这个改到 [www.pushplus.plus](http://www.pushplus.plus) 的，另外没有出现消息异常
> > ![Screenshot_2021-08-23-20-56-25-240_com tencent mm](https://user-images.githubusercontent.com/62287903/130451015-b78abbac-8cf9-4f4f-831e-c9ed7d23a850.jpg)
> 
> 不太清楚 我昨天才开始用的pushplus
> 您可以看下另一个 issue 也是反应这个问题的
> 用 [www.pushplus.plus](http://www.pushplus.plus) 就会提示无效的用户 token
> 用这个 pushplus.hxtrip.com 就是 200，而且只有 html 和 json
> 难道说 pushplus 有两套用户系统对应两个域名？那是否得考虑新增一个变量了

就是两套系统来的，老的那个理应已经废弃掉了，之前公众号发了公告的，这个 pushplus.plus 是新的，建议换成用这个，你需要去新网站获取 token

**Comment by AXdouB** [comment]
> > > 你确定是新域名？明明是老域名啊，之前就是从这个改到 [www.pushplus.plus](http://www.pushplus.plus) 的，另外没有出现消息异常
> > > ![Screenshot_2021-08-23-20-56-25-240_com tencent mm](https://user-images.githubusercontent.com/62287903/130451015-b78abbac-8cf9-4f4f-831e-c9ed7d23a850.jpg)
> > 
> > 
> > 不太清楚 我昨天才开始用的pushplus
> > 您可以看下另一个 issue 也是反应这个问题的
> > 用 [www.pushplus.plus](http://www.pushplus.plus) 就会提示无效的用户 token
> > 用这个 pushplus.hxtrip.com 就是 200，而且只有 html 和 json
> > 难道说 pushplus 有两套用户系统对应两个域名？那是否得考虑新增一个变量了
> 
> 就是两套系统来的，老网站的 token 无法用于新接口，老的那个网站理应已经废弃掉了，之前公众号发了公告的，这个 pushplus.plus 是新的，建议换成用这个，你需要去新网站获取 token

感谢告知！旧网站在百度的SEO排名是第一，所以我当时就直接使用旧系统了，而且旧网站也没提示。

**Comment by Yaklo** [comment]
原来我用的是旧网站😂
