### ISSUE TITLE
第三方库导包推荐

### ISSUE THREAD

**Issue by Mashiro2000** [y1ndan/genshinhelper#49]
作者你好，你的代码逻辑很不错，我这边推荐个语法糖，你可以尝试使用以下语法，实现第三方库自行安装，并重新执行
```
 try:
    import requests
except ModuleNotFoundError:
    print("缺少requests依赖！程序将尝试安装依赖！")
    os.system("pip3 install requests -i https://pypi.tuna.tsinghua.edu.cn/simple")
    os.execl(sys.executable, 'python3', __file__, *sys.argv)
```

**Comment by y1ndan** [comment]
这个是用在什么情景？

`pip install`不是默认安装依赖了吗？

**Comment by Mashiro2000** [comment]
> 这个是用在什么情景？
> 
> `pip install`不是默认安装依赖了吗？

目前，我使用的情景是，提供脚本，用户只需要双击运行即可安装第三方库，并重新执行自身(有些用户确实连`pip install`都不会)

**Comment by y1ndan** [comment]
这个导入思路很好，学到了！不过感觉适合单文件的项目，不知道怎么引入本项目哈哈。
