### ISSUE TITLE
有没有关于微博部分的进一步说明？

### ISSUE THREAD

**Issue by ProblemFactory** [y1ndan/genshinhelper#5]
比如如何获取Cookie，aid，s三个信息，三个信息分别应该是什么格式？我试了下用mumu+fiddler获取微博国际版的超话信息，然而请求里并没有cookie，而我用m.weibo.cn网页获得的cookie也不对。我也尝试在微博国际版中重新登陆，截取到的response里有一个Cookie字段，也不能用。我还试了下直接按照代码里面的格式发起了个get请求，发现只要get parameter里没有gsid和from就会导致验证失败，而并不需要发送Cookie。
作者能不能详细解释下这部分到底应该怎么操作？我现在超话签到的部分一直提示Empty follow data，postman按照代码里格式发的请求返回要么是-105客户端身份校验失败（采用微博国际版登录response中的Cookie），要么是-100您的身份已失效，请重新登录（采用m.weibo.cn网页的Cookie）。

**Comment by y1ndan** [comment]
如果是使用iOS设备，可参考这个视频：[微博国际版iOS抓包教程](https://b23.tv/3cj7vG)

**Comment by everything411** [comment]
我今天下午试了下，签到不需要cookie，领取兑换码需要cookie，签到部分缺少gsid和from验证就会失败，手机抓包补上去就能签到了，兑换码领取的部分的cookie应该是ka.sina.com.cn的cookie，而不是m.weibo.cn的cookie

**Comment by ProblemFactory** [comment]
兑换码的部分我没问题。gsid和from要改代码才能加上去吧？我是docker部署，不是很好改代码，作者会不会更新一下代码里的请求格式？

**Comment by ProblemFactory** [comment]
> 如果是使用iOS设备，可参考这个视频：[微博国际版iOS抓包教程](https://b23.tv/3cj7vG)

可以看到这个视频里抓到的请求里也没有Cookie的

**Comment by everything411** [comment]
> 
> 
> > 如果是使用iOS设备，可参考这个视频：[微博国际版iOS抓包教程](https://b23.tv/3cj7vG)
> 
> 我按照这视频里的方法在Mumu模拟器上操作，fiddler上抓的包里的header里都没有Cookie。就像这个视频里前面一半抓到的包一样。后面一半有Cookie的那个portal.php的链接我这边也不带Cookie。

对，微博客户端是不用cookie的，目前我是改了代码来部署的，我用的阿里云白嫖的函数计算，上传之后是可以在线编辑的，需要修改的地方不多，就是config.py里从环境变量读取配置和weibo.py里发送请求

**Comment by ProblemFactory** [comment]
用iOS版微博国际版解决了，看来Android和iOS上的微博国际版API差很多。。。

**Comment by everything411** [comment]
@y1ndan 请问作者可以为安卓客户端做一下适配吗？并没有苹果的设备qaq

**Comment by lucky7genius** [comment]
我是iphone12 ios14.6 国际版微博4.3.3.2版本，使用thor或者stream都获取不到任何数据包，但是普通版微博的aid和s都可以获取。请问我应该怎么做才能抓到国际版的包或者怎样修改weibo.py才能使用普通微博的aid和s进行签到？

**Comment by y1ndan** [comment]
>使用thor或者stream都获取不到任何数据包

测试了stream是可以抓到国际版的，看下是不是https抓包没有设置。
